services:
  api:
    build: .
    container_name: mc-manager
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_DATA_ROOT}:/data/minecraft
    env_file:
      - .env
    environment:
      DATA_ROOT: /data/minecraft
    restart: unless-stopped
